# konfiguracja aplikacji magvid-authentication-service pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8087
spring:
  application:
    name: magvid-streaming-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  security:
    sessions: never
