# konfiguracja aplikacji magvid-content-management-service pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8087
spring:
  application:
    name: magvid-management-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
