# konfiguracja aplikacji magvid-proxy pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8080
spring:
  application:
    name: magvid-proxy
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
hystrix:
  command:
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

zuul:
  routes:
    rating-service:
      path: /rating-service/**
      sensitive-headers: Set-Cookie,Authorization
hystrix:
  command:
    rating-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

zuul:
  routes:
    magvid-discovery:
      path: /magvid-discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
hystrix:
  command:
    magvid-discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000