# konfiguracja aplikacji magvid-proxy pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8080
spring:
  application:
    name: magvid-proxy
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  security:
    sessions: always

zuul:
  routes:
    magvid-discovery:
      path: /magvid-discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
    magvid-authentication-service:
      path: /magvid-authentication-service/**
      sensitive-headers: Set-Cookie,Authorization
    magvid-search-service:
      path: /magvid-search-service/**
      sensitive-headers: Set-Cookie,Authorization
    magvid-streaming-service:
      path: /magvid-streaming-service/**
      sensitive-headers: Set-Cookie,Authorization
    magvid-content-management-service:
      path: /magvid-content-management-service/**
      sensitive-headers: Set-Cookie,Authorization
    magvid-administration-service:
      path: /magvid-administration-service/**
      sensitive-headers: Set-Cookie,Authorization

hystrix:
  command:
    magvid-discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-authentication-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-search-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-streaming-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-content-management-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-administration-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
