# konfiguracja aplikacji magvid-search-service pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8084
spring:
  application:
    name: magvid-search-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  security:
    sessions: never
