# konfiguracja aplikacji magvid-administration-service pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8086
spring:
  application:
    name: magvid-administration-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
