# konfiguracja aplikacji magvid-discovery pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8082
spring:
  application:
    name: magvid-discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
