# konfiguracja aplikacji magvid-proxy pobierana zdalnie przez serwer konfiguracyjny
server:
  port: 8080
spring:
  application:
    name: magvid-proxy
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    book-service:
      path: /magvid-authentication-service/**
      sensitive-headers: Set-Cookie,Authorization
    rating-service:
      path: /magvid-search-service/**
      sensitive-headers: Set-Cookie,Authorization
    magvid-discovery:
      path: /magvid-discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082

hystrix:
  command:
    magvid-authentication-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-search-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    magvid-discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000